### ISSUE TITLE
Test jPurify with Zepto

### ISSUE THREAD

**Issue by fhemberger** [cure53/jPurify#3]
It would be interesting to see if jPurify also works on Zepto (a slimmer replacement for jQuery, especially used on mobile). I can't recall any other replacement, which has a noticeable user base size.

**Comment by cure53** [comment]
I am wondering if Zepto is relevant enough to be covered. We can cover it, but it would require some effort because its internals are slightly different. What do you think?

**Comment by fhemberger** [comment]
No, I guess not. I will close this until someone explicitly needs support for Zepto.
